version: '3.9'
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
services: 
# Jaeger
  toltek_jaeger:
    image: jaegertracing/all-in-one:1.52
    container_name: ${JAEGER_HOST}
    command:
      - "--memory.max-traces=8000"
      - "--query.base-path=/jaeger/ui"
      - "--prometheus.server-url=${PROMETHEUS_DOMAIN}"
      - "--prometheus.query.normalize-calls=true"
      - "--prometheus.query.normalize-duration=true"
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    ports:
      - ${JAEGER_PORT_UI} # Jaeger UI
      - ${JAEGER_PORT_OLTP}:4317  # OTLP gRPC default port
    environment:
      - METRICS_STORAGE_TYPE=prometheus
    logging: *logging
  # Prometheus
  toltek_prometheus:
    image: quay.io/prometheus/prometheus:v2.48.1
    container_name: ${PROMETHEUS_HOST}
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --enable-feature=exemplar-storage
      - --enable-feature=otlp-write-receiver
    volumes:
      - $PWD/config/prometheus/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    deploy:
      resources:
        limits:
          memory: 300M
    ports:
      - ${PROMETHEUS_PORT}:9090
    logging: *logging
  # Grafana
  toltek_grafana:
    image: grafana/grafana
    container_name: ${GRAFANA_HOST}
    restart: always   
    volumes:
      - $PWD/config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - $PWD/config/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      default:
        ipv4_address: ${GRAFANA_IP}
    logging: *logging
  # Seq
  toltek_seq:
    image: datalust/seq:latest
    container_name: ${SEQ_HOST}
    restart: always
    ports:
      - ${SEQ_PORT_UI}:80
      - ${SEQ_PORT}:5341
    environment:
      - ACCEPT_EULA=Y   
      - SEQ_API_CANONICALURI=${SEQ_DOMAIN}
      - SEQ_FIRSTRUN_ADMINUSERNAME=${SEQ_USERNAME}
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_PASS}
    volumes:
      - $PWD/data/seq-data:/data
    networks:
      default:
        ipv4_address: ${SEQ_IP}
