global:
  evaluation_interval: 30s
  scrape_interval: 5s
scrape_configs:
- job_name: otel
  honor_labels: true
  static_configs:
  - targets:
    - 'toltek_otelcol:9464'
- job_name: otel-collector
  static_configs:
  - targets:
    - 'toltek_otelcol:8888'
