extensions:
  health_check:
  # pprof:
  # zpages:
  #   endpoint: :55679
  headers_setter:
    headers:
      - action: upsert
        key: X-Seq-ApiKey
        value: ${SEQ_PASS}

receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
  zipkin:

exporters:
# Data sources: traces, metrics, logs
  file/traces:
    path: /log/traces.log
  file/metrics:
    path: /log/metrics.log
  file/logs:
    path: /log/logs.log
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: ${JAEGER_ENDPOINT_OTLP}
    tls:
      insecure: true
  otlphttp/seq:
    endpoint: ${SEQ_ENDPOINT_OTLP}
    auth:
      authenticator: headers_setter
#  prometheus:
#    endpoint: toltek_prometheus:9090
#    namespace: default
  otlphttp/prometheus:
    endpoint: ${PROMETHEUS_ENDPOINT_OTLP}
    tls:
      insecure: true
  zipkin:
    endpoint: ${ZIPKIN_ENDPOINT_OTLP}
  loki:
    endpoint: "${LOKI_ENDPOINT_OTLP}"
    tls:
      insecure: true

processors:
  batch:
  filter/ottl:
    error_mode: ignore
    metrics:
      metric:
        # FIXME: remove when a Metrics View is implemented in the checkout and productcatalog components
        # or when this issue is resolved: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/3071
        - 'name == "rpc.server.duration"'
  transform:
    metric_statements:
      - context: metric
        statements:
          # FIXME: remove when this issue is resolved: https://github.com/open-telemetry/opentelemetry-java/issues/4834
          - set(description, "") where name == "queueSize"
          # FIXME: remove when this issue is resolved: https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1958
          - set(description, "") where name == "http.client.duration"
       


connectors:
  spanmetrics:

service:
  extensions: [headers_setter ]
  pipelines:
    traces:
      receivers:
        - otlp
#        - zipkin
      processors: [batch]
      exporters:       
        - spanmetrics
        - otlp/jaeger
        - zipkin 
#        - file/traces
#        - debug 
    metrics:
      receivers: 
        - spanmetrics
        - otlp 
      processors: 
        - filter/ottl
        - transform
        - batch
      exporters: 
      - otlphttp/prometheus 
#      - file/metrics
#      - debug
    logs:
      receivers: 
        - otlp
      processors: [batch]
      exporters: 
        - otlphttp/seq
        - loki
#        - file/logs
        - debug
#    extensions:
#     - health_check
#     - zpages
