apiVersion: 1
datasources:
  - name: Prometheus
    uid: webstore-metrics
    type: prometheus
    url: http://toltek_prometheus:9090
    editable: true
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: webstore-traces
          name: trace_id
        - url: http://toltek_jaeger:8080/jaeger/ui/trace/$${__value.raw}
          name: trace_id
          urlDisplayLabel: View in Jaeger UI
