apiVersion: 1
datasources:
  - name: MongoDB
    type: grafana-mongodb-datasource
    access: proxy
    basicAuth: false
    editable: true
    enabled: true
    jsonData:
      connection: mongodb://toltek_mongodb:28017
      user: admin
    secureJsonData:
      password: toltek_mongodb
