apiVersion: 1
datasources:
  - name: Prometheus
    uid: webstore-metrics
    type: prometheus
    url: ${PROMETHEUS_ENDPOINT_LOCAL}
    editable: true
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: webstore-traces
          name: trace_id
        - url: ${JAEGER_ENDPOINT_LOCAL}/jaeger/ui/trace/$${__value.raw}
          name: trace_id
          urlDisplayLabel: View in Jaeger UI
